In [20]:
num =[]
num = num + [10, 5, 3]


print(num)

[10, 5, 3]


In [16]:
palabras = ["adidas","colombia","argentina", "brasil", "alemania"]

palabras.pop(-2,) #se esta eliminado un elemento de la lista
palabras.pop(2,)

print(palabras)

['adidas', 'colombia', 'alemania']


In [21]:
palabras = ["hola", "hello", "ciao", "salute", "hello"]

palabras.remove("hello") #se esta eliminado un elemento de la lista
palabras.remove("hola")

print(palabras)#con esto imprime las palabras o elementos que no fueron eliminados

['ciao', 'salute', 'hello']


In [25]:
personas = [
    {"nombre": "Juan", "documento": "12345678"},
    {"nombre": "Ana", "documento": "23456789"},
    {"nombre": "Luis", "documento": "34567890"}
]


for persona in personas:
    print(f"Nombre: {persona['nombre']}, Documento: {persona['documento']}")

Nombre: Juan, Documento: 12345678
Nombre: Ana, Documento: 23456789
Nombre: Luis, Documento: 34567890


In [37]:
nombres = []
identificaciones = []
direcciones = []

# Definir el tamaño de las listas
tamaño = 3

# Leemos datos y agregamos a las listas
for i in range(tamaño):
    print(f"Ingrese los datos de la persona {i + 1}")
    nombre = input("Nombre: ")
    identificacion = input("Identificación: ")
    direccion = input("Dirección: ")

    # Agregar a las listas correspondientes
    nombres.append(nombre)  # Aquí se usa la lista "nombres" correctamente
    identificaciones.append(identificacion)  # Usamos "identificaciones"
    direcciones.append(direccion)  # Usamos "direcciones"

# Ahora mostramos las listas
for i in range(tamaño):
    print(f"Mostrando los datos de la persona {i + 1}")
    print("Nombre:", nombres[i])
    print("Identificación:", identificaciones[i])
    print("Dirección:", direcciones[i])

Ingrese los datos de la persona 1
Nombre: asdasd
Identificación: 12312
Dirección: asdasdas
Ingrese los datos de la persona 2
Nombre: asdasd
Identificación: 123321
Dirección: asdasd2
Ingrese los datos de la persona 3
Nombre: asdas
Identificación: 1445
Dirección: asdasd25
Mostrando los datos de la persona 1
Nombre: asdasd
Identificación: 12312
Dirección: asdasdas
Mostrando los datos de la persona 2
Nombre: asdasd
Identificación: 123321
Dirección: asdasd2
Mostrando los datos de la persona 3
Nombre: asdas
Identificación: 1445
Dirección: asdasd25


In [43]:
import numpy as np

# Lista con los números correctamente separados por comas
lst = [10, 20, 30, 40, 50]

# Convertir la lista a un arreglo de NumPy
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)

Vector creado desde una lista:
[10 20 30 40 50]


In [45]:
import numpy as np

# Lista con los números correctamente separados por comas
lst = ["DARIAN", "PAKA", "LORENA", "BRAYAN"]

# Convertir la lista a un arreglo de NumPy
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)

Vector creado desde una lista:
['DARIAN' 'PAKA' 'LORENA' 'BRAYAN']


In [48]:
import numpy as np

# Lista con los números correctamente separados por comas
lst = ["PERA", "BANANO","MANZANA"]

# Convertir la lista a un arreglo de NumPy
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)

Vector creado desde una lista:
['PERA' 'BANANO' 'MANZANA']


In [51]:
import numpy as np
lst = [[10], [20], [30], [40], [50]]
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)


Vector creado desde una lista:
[[10]
 [20]
 [30]
 [40]
 [50]]


In [53]:
import numpy as np
lst = [["ITZZA"], ["NICOLAS"], ["VELANDIA"], ["DANIEL"], ["ARTEAGA"]]
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)

Vector creado desde una lista:
[['ITZZA']
 ['NICOLAS']
 ['VELANDIA']
 ['DANIEL']
 ['ARTEAGA']]


In [55]:
import numpy as np
lst = [["PIZZA"], ["SALCHIPAPA"], ["CHORIPERRO"], ["COMBINADO"], ["AGUA DE PANELA"]]
vctr = np.array(lst)

# Mostrar el vector creado
print("Vector creado desde una lista:")
print(vctr)

Vector creado desde una lista:
[['PIZZA']
 ['SALCHIPAPA']
 ['CHORIPERRO']
 ['COMBINADO']
 ['AGUA DE PANELA']]


In [59]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 1,2,3,4,5]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la suma
vctr_add = vctr1+vctr2
print("la respues es: " , vctr_add)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 2 3 4 5]
la respues es:  [11 22 33 44 55]


In [61]:
import numpy as np

lista1 = [10,20,30,40,50]
lista2=[ 1,2,3,4,5,6 ,7]
# en este caso nos dara sintax error por que el tamaño de las listas es diferente

vctr1 =np.array(lista1)
vctr2 =np.array(lista2)

print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)


vctr_add = vctr1+vctr2
print("la respues es: " , vctr_add)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [63]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 1,2,3,4,5]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la resta
vctr_add = vctr1-vctr2
print("la respues es: " , vctr_add)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 2 3 4 5]
la respues es:  [ 9 18 27 36 45]


In [65]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 1,2,3,4,5]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la multiplicación
vctr_add = vctr1*vctr2
print("la respues es: " , vctr_add)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 2 3 4 5]
la respues es:  [ 10  40  90 160 250]


In [67]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 1,2,3,4,5]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la divicion
vctr_add = vctr1/vctr2
print("la respues es: " , vctr_add)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 2 3 4 5]
la respues es:  [10. 10. 10. 10. 10.]


In [71]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 1,1,1,1,1]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la operación
vctr_dot = vctr1.dot(vctr2)
print("la respues es: " , vctr_dot)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[1 1 1 1 1]
la respues es:  150


In [73]:
import numpy as np

lista1 = [10,20,30,40,50] # se crean las listas
lista2=[ 2,2,2,2,2]

vctr1 =np.array(lista1)
vctr2 =np.array(lista2) # se crean los vectores

#se imprime los valores de cada vector segun las lista
print("vector creado de la lista 1:")
print(vctr1)
print("vector creado de la lista 2:")
print(vctr2)

# se  realiza la operación
vctr_dot = vctr1.dot(vctr2)
print("la respues es: " , vctr_dot)

vector creado de la lista 1:
[10 20 30 40 50]
vector creado de la lista 2:
[2 2 2 2 2]
la respues es:  300
